name: Validation
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    name: Full Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint Data
        run: |
          yarn --frozen-lockfile
          yarn style:check

      - name: Check Build and Tests
        run: |
          yarn build
          yarn test
